### PR TITLE
Fix multithreading issue in biome serialization

### LINKED ISSUE #3: Missing biome data deletes chunks
During testing, some chunks in a world I loaded were regenerated and this error was logged:
```
java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2378.method_10250(net.minecraft.class_2960)" because "this.val$biomes" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.2) ~[?:?]
	at net.minecraft.class_2852$Anonymous$3a790e01c5b0465ab46ea3049050128e.decode(ChunkSerializerMixin.java:116) ~[?:?]
	at com.mojang.serialization.Codec$4.decode(Codec.java:217) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.codecs.ListCodec.lambda$decode$2(ListCodec.java:46) ~[datafixerupper-5.0.28.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at com.mojang.serialization.codecs.ListCodec.lambda$decode$4(ListCodec.java:45) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.codecs.ListCodec.decode(ListCodec.java:39) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.codecs.FieldDecoder.decode(FieldDecoder.java:29) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.MapCodec$1.decode(MapCodec.java:34) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$3.decode(RecordCodecBuilder.java:248) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.decode(RecordCodecBuilder.java:107) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.MapDecoder.lambda$compressedDecode$0(MapDecoder.java:52) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.DataResult.lambda$flatMap$10(DataResult.java:138) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.DataResult.flatMap(DataResult.java:136) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.MapDecoder.compressedDecode(MapDecoder.java:52) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.decode(MapCodec.java:91) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.Decoder$1.decode(Decoder.java:49) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.Codec$2.decode(Codec.java:71) ~[datafixerupper-5.0.28.jar:?]
	at com.mojang.serialization.Decoder.parse(Decoder.java:18) ~[datafixerupper-5.0.28.jar:?]
	at net.minecraft.world.ChunkSerializer.deserialize(ChunkSerializer:115) ~[?:?]
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.md122ad9$lambda$loadChunk$2$2c(ThreadedAnvilChunkStorage:18043) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646) [?:?]
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1840) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) [?:?]
```

Full logs: https://mclo.gs/T87K78l
[latest.log](https://github.com/BasiqueEvangelist/FlashFreeze/files/9273926/latest.log)

It seems that the static field trickery done here
https://github.com/BasiqueEvangelist/FlashFreeze/blob/27c7bfdde0af149bfb6ed2995e11673ba7870bb9/src/main/java/me/basiqueevangelist/flashfreeze/mixin/ChunkSerializerMixin.java#L116

Does _not_ play nice with C2ME deserializing multiple chunks at once.

### PR DESCRIPTION
**Pull request by magneticflux-**
Also replace casts and class checks with correct `DynamicOps` usage

Closes #3

### CODE REVIEW

**Comment by BasiqueEvangelist** [comment]
Why did you make UnknownBiome extend `RegistryEntry<Biome>`?
The point of UnknownReplacers is that they're supposed to be replaced before casts

**Comment by magneticflux-** [comment]
Because it got rid of a type check and cast 🤷

Should it instead be cast to `RegistryEntry` without actually implementing it so it errors at runtime if not class checked?

**Comment by BasiqueEvangelist** [comment]
> Because it got rid of a type check and cast shrug
> 
> Should it instead be cast to `RegistryEntry` without actually implementing it so it errors at runtime if not class checked?

Yeah, that's how it works with `UnknownBlockState`s too

**Review by BasiqueEvangelist — APPROVED** [review]
Very nice, thank you for the PR!
I'm going to merge this tomorrow since I really don't want to be merging PRs at 3 AM

**Pull request merged**
